version: "3.9"

services:
  postgres: # name of the service
    image: postgres:15
    container_name: fraud-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # inside .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: